name: videostreaming
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  appinio_video_player: ^1.2.2
  cached_video_player_plus: ^3.0.3
  chewie: ^1.8.3
  flick_video_player: ^0.9.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  video_player: ^2.9.1
  video_player_android: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
cachedflickvideoplayer:
git:
  url: https://github.com/elgsylvain85/cachedflickvideoplayer.git